name: Build & Deploy
on:
  push:
    branches: ["master"]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: Install Node dependencies
        run: npm i
      - name: Build frontend assets
        run: npm run prod
      - uses: "shivammathur/setup-php@v2"
        with:
          php-version: "8.4"
      - uses: "ramsey/composer-install@v3"
        with:
          composer-options: --prefer-dist --no-progress
      - name: Build the site
        run: php hyde build --pretty-urls --run-prettier
      - name: Upload site artifact
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: _site
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
        with:
          ref: "gh-pages"
          token: ${{ secrets.GH_TOKEN }}
      - name: Empty site directory
        run: rm -rf *
      - name: Download site artifact
        uses: actions/download-artifact@v4
        with:
          name: site
          path: "."
      - name: Create .nojekyll file
        run: touch .nojekyll
      - name: Create CNAME
        run: echo "www.notakrista.com" > CNAME
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          add: "."
          message: "Upload compiled site ${{ github.sha }}"
